version: "3"

tasks:
  default:
    desc: List all
    cmds:
      - task --list-all
    silent: true

  tidy:
    desc: Mod tidy
    cmds:
      - go mod tidy
    silent: true

  test:
    desc: Run tests
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - go test -v -count=1 {{.CLI_ARGS}}
    silent: true
