version: 3

tasks:
  default:
    desc: list all
    cmds:
      - task --list-all
    silent: true

  test:
    desc: run go test
    cmds:
      - go test -v -count=1 {{.USER_WORKING_DIR}}/{{.CLI_ARGS}}
    silent: true
